version: '3'
services:
  postgres:
    #version postgres 9.6.9
    image: postgres
    container_name: "postgres"
    restart: always
    volumes:
      - ./app:/dados/postgree/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: postgres
    ports:
      - 54320:5432

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./app:/dados/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  micro_service:
    build: ./
    hostname: micro_service
    container_name: "micro_service"
    restart: always
    ports:
      - 8085:8080
    links:
      - postgres
      - rabbitmq

