CREATE TABLE votante (
  id serial CONSTRAINT PKVOTANTE PRIMARY KEY,
  cpf VARCHAR (11) NOT NULL,
  id_pauta INTEGER
);

ALTER TABLE votante add CONSTRAINT FK1VOTANTE FOREIGN KEY (id_pauta) REFERENCES pauta(id);