CREATE TABLE pautaresultado (
  id serial CONSTRAINT PKPAUTARESULTADO PRIMARY KEY,
  id_pauta INTEGER,
  nm_pauta VARCHAR (30) NOT NULL,
  de_pauta VARCHAR(300) NOT NULL,
  votos_sim INTEGER,
  votos_nao INTEGER
);

ALTER TABLE voto add CONSTRAINT FK1PAUTARESULTADO FOREIGN KEY (id_pauta) REFERENCES pauta(id);
